name: Strapi CI - Docker Build and Push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: vikky17/strapi
  AWS_REGION: ap-south-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Generate image tag
      id: vars
      run: echo "tag=latest-$(date +%s)" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:$tag .

    - name: Push Docker image
      run: docker push $IMAGE_NAME:$tag

    - name: Save image URI for deploy
      run: echo "image_uri=$IMAGE_NAME:$tag" > image.txt

    - name: Upload image URI artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-info
        path: image.txt
