name: CD - Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        
      - name: Terraform Plan
        run: terraform plan -var="docker_image_tag=${{ github.event.inputs.image_tag }}"
        working-directory: ./terraform
        
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="docker_image_tag=${{ github.event.inputs.image_tag }}"
        working-directory: ./terraform
        
      - name: Get EC2 Public IP
        id: output
        run: echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform
        
      - name: Display Access Information
        run: |
          echo "🚀 Deployment Complete!"
          echo "Strapi URL: http://${{ steps.output.outputs.ec2_ip }}:1337"
          echo "SSH Access: ssh -i your-key.pem ubuntu@${{ steps.output.outputs.ec2_ip }}"